// <auto-generated />
namespace MarriageRegitrar.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Migration4_From_Ahasanul_Banna_PC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Migration4_From_Ahasanul_Banna_PC));
        
        string IMigrationMetadata.Id
        {
            get { return "201810101431126_Migration4_From_Ahasanul_Banna_PC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
